
spring:
  application:
    name: seller-service
  data:
    mongodb:
      host: ${MONGODB_URL:localhost}
      port: ${MONGODB_PORT:27017}
      database: products
      auto-index-creation: true


server:
  servlet:
    context-path: /api
  port: 8020

logging:
  level:
    root: ${LOGGIN_LEVEL:info}

management:
  endpoints:
    web:
      exposure:
        include: "*"